### ISSUE TITLE
How To Access Kibana From ELB

### ISSUE THREAD

**Issue by beibeiJ** [opentelekomcloud-docs/cloud-search-service#36]
Issue on page:        https://github.com/opentelekomcloud-docs/cloud-search-service/blob/main/umn/source/faqs/how_to_access_kibana_from_elb.rst

hyperlink with 404 error
![Screenshot 2023-02-08 at 13 38 24](https://user-images.githubusercontent.com/20110950/217532269-5ab7b8d9-29cc-42c7-8825-84c798494a5c.png)

**Comment by vineet-pruthi** [comment]
Thank you Beibei for addressing it, i have removed this link since its not available.
